server:
  port: 1111
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true

  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    com:
      zensar: debug
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/studentdb
    username: syed
    password: syed
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
 
#  security:
#    user:
#      name: user
#      password: 1234